title: J.D. Bean
description: > # this means to ignore newlines until "baseurl:"
  A blog covering the journey of a tech-lawyer studying software development.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jdbean.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: J.D. Bean # add your name
author-img: avatar.jpg # add your photo
about-author: Lawyer turned full-stack developer. Passionate about free and open source software, privacy, and security. Always hungry to keep learning. # add description
social-twitter: bean_jd
# social-facebook: # add your Facebook handle
social-github: jdbean # add your Github handle
social-linkedin: jonathan-bean-155725b4
social-email: jonathandbean@gmail.com

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "vendor"]
